# Generated by Django 3.1 on 2021-04-24 18:06

import core.formatChecker
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sld1', core.formatChecker.ContentTypeRestrictedFileField(blank=True, default='banner/default/sld-1min.png', null=True, upload_to='banner', verbose_name='Slide 1')),
                ('sld2', core.formatChecker.ContentTypeRestrictedFileField(blank=True, default='banner/default/sld2min.png', null=True, upload_to='banner', verbose_name='Slide 2')),
                ('sld3', core.formatChecker.ContentTypeRestrictedFileField(blank=True, default='banner/default/sld1min.png', null=True, upload_to='banner', verbose_name='Slide 3')),
                ('sld4', core.formatChecker.ContentTypeRestrictedFileField(blank=True, default='banner/default/sld3.png', null=True, upload_to='banner', verbose_name='Slide 4')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
