# Generated by Django 3.1 on 2020-08-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phrase', models.TextField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'ordering': ['-name'],
            },
        ),
    ]
