# Generated by Django 3.1 on 2021-04-21 22:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sld1', models.ImageField(blank=True, default='./staticfiles/core/img/sld-1min.png', null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 1')),
                ('sld2', models.ImageField(blank=True, default='./staticfiles/core/img/sld2min.png', null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 2')),
                ('sld3', models.ImageField(blank=True, default='./staticfiles/core/img/sld1min.png', null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 3')),
                ('sld4', models.ImageField(blank=True, default='./staticfiles/core/img/sld3.png', null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 4')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
