# Generated by Django 3.1 on 2021-04-21 23:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sld1',
            field=models.ImageField(blank=True, default='./staticfiles/core/img/sld-1min.png', null=True, upload_to='banner', validators=[core.validators.validate_file_size], verbose_name='Slide 1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld2',
            field=models.ImageField(blank=True, default='./staticfiles/core/img/sld2min.png', null=True, upload_to='banner', validators=[core.validators.validate_file_size], verbose_name='Slide 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld3',
            field=models.ImageField(blank=True, default='./staticfiles/core/img/sld1min.png', null=True, upload_to='banner', validators=[core.validators.validate_file_size], verbose_name='Slide 3'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld4',
            field=models.ImageField(blank=True, default='./staticfiles/core/img/sld3.png', null=True, upload_to='banner', validators=[core.validators.validate_file_size], verbose_name='Slide 4'),
        ),
    ]
