# Generated by Django 3.1 on 2020-08-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='Bussiness',
        ),
    ]
