# Generated by Django 3.1 on 2021-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_bussiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sld1', models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', verbose_name='Slide 1')),
                ('sld2', models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', verbose_name='Slide 2')),
                ('sld3', models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', verbose_name='Slide 3')),
                ('sld4', models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', verbose_name='Slide 4')),
            ],
        ),
    ]
