# Generated by Django 3.1 on 2021-04-21 01:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld1',
            field=models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld2',
            field=models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld3',
            field=models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 3'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sld4',
            field=models.ImageField(blank=True, null=True, upload_to='./staticfiles/core/img/banner', validators=[core.validators.validate_file_size], verbose_name='Slide 4'),
        ),
    ]
