# Generated by Django 3.1 on 2020-08-17 23:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('city', models.CharField(max_length=100, verbose_name='Municipio')),
                ('locality', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Código postal')),
                ('colony', models.CharField(max_length=100, verbose_name='Colonia')),
                ('street', models.CharField(max_length=100, verbose_name='Calle')),
                ('ext_number', models.CharField(max_length=100, verbose_name='Número exterior')),
                ('int_number', models.CharField(max_length=100, verbose_name='Número interior')),
                ('to_home', models.BooleanField(verbose_name='Servicio a domicilio')),
                ('delivery_options', models.CharField(choices=[('N', 'Colonias cercanas'), ('C', 'Toda la ciudad'), ('O', 'Otras ciudades')], max_length=1, verbose_name='Entrega en:')),
                ('platform', models.CharField(max_length=300, verbose_name='Url Plataforma')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('cellphone', models.CharField(max_length=100, verbose_name='Telefono Móvil')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('activity', models.CharField(max_length=100, verbose_name='Actividad económica')),
                ('subactivity', models.CharField(max_length=100, verbose_name='Actividad específica')),
                ('image', models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Imagen')),
                ('let_me_know_more', models.BooleanField(verbose_name='Desea contarnos mas')),
                ('join', models.BooleanField(verbose_name='Quiere se parte')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('payment_method', models.ManyToManyField(to='market.Payment', verbose_name='Categorías')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Empresa solidaria',
                'verbose_name_plural': 'Empresas solidarias',
                'ordering': ['-created'],
            },
        ),
    ]
