# Generated by Django 3.1 on 2021-04-22 00:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product1',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Producto 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product2',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Producto 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product3',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Producto 3'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product4',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Producto 4'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product5',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Producto 5'),
        ),
        migrations.AlterField(
            model_name='company',
            name='product6',
            field=models.ImageField(blank=True, default='company/default/noimage.jpg', null=True, upload_to='company', validators=[core.validators.validate_file_size], verbose_name='Producto 6'),
        ),
    ]
