# Generated by Django 3.1 on 2020-08-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200817_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_method',
            field=models.ManyToManyField(to='market.Payment', verbose_name='Metodo de pago'),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.city', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.locality', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.city', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='colony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.colony', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.locality', verbose_name='Localidad'),
        ),
    ]
