# Generated by Django 3.1 on 2020-08-18 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200818_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created'], 'verbose_name': 'Actividad económica', 'verbose_name_plural': 'Actividades económica'},
        ),
        migrations.AlterModelOptions(
            name='subactivity',
            options={'ordering': ['-created'], 'verbose_name': 'Subactividad', 'verbose_name_plural': 'Subactividades'},
        ),
        migrations.AddField(
            model_name='subactivity',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.activity', verbose_name='Actividad'),
        ),
    ]
