# Generated by Django 3.1 on 2020-08-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200818_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactivity',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.activity', verbose_name='Actividad'),
        ),
    ]
