# Generated by Django 3.1 on 2020-08-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200818_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subactivity',
            name='activity',
        ),
    ]
