# Generated by Django 3.1 on 2020-08-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_subactivity_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subactivity',
        ),
        migrations.DeleteModel(
            name='SubActivity',
        ),
    ]
