# Generated by Django 3.1 on 2020-08-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20200818_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Subactividad',
                'verbose_name_plural': 'Subactividades',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='subactivity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.subactivity', verbose_name='Actividad especifica'),
        ),
    ]
