# Generated by Django 3.1 on 2020-08-18 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20200818_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colony',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='colony',
        ),
        migrations.RemoveField(
            model_name='company',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subactivity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='city',
        ),
        migrations.RemoveField(
            model_name='subactivity',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Colony',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SubActivity',
        ),
    ]
