# Generated by Django 3.1 on 2020-08-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20200818_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='activity',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='market.city', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='colony',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='market.colony', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='delivery_options',
            field=models.CharField(blank=True, choices=[('N', 'Colonias cercanas'), ('C', 'Toda la ciudad'), ('O', 'Otras ciudades')], max_length=1, null=True, verbose_name='Entrega en:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ext_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='company',
            name='int_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número interior'),
        ),
        migrations.AlterField(
            model_name='company',
            name='join',
            field=models.BooleanField(blank=True, null=True, verbose_name='Quiere se parte'),
        ),
        migrations.AlterField(
            model_name='company',
            name='let_me_know_more',
            field=models.BooleanField(blank=True, null=True, verbose_name='Desea contarnos mas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='market.locality', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='platform',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Url Plataforma'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subactivity',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.subactivity', verbose_name='Actividad especifica'),
        ),
        migrations.AlterField(
            model_name='company',
            name='to_home',
            field=models.BooleanField(blank=True, null=True, verbose_name='Servicio a domicilio'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.city', verbose_name='Municipio'),
        ),
    ]
