# Generated by Django 3.1 on 2020-08-26 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20200818_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created'], 'verbose_name': 'Empresa sonorense', 'verbose_name_plural': 'Empresas sonorenses'},
        ),
        migrations.AddField(
            model_name='company',
            name='operation_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 18, 35, 35, 326771), verbose_name='Inicio de operaciones'),
        ),
        migrations.AddField(
            model_name='company',
            name='registerSAT',
            field=models.BooleanField(default=True, verbose_name='Registrado en el SAT'),
        ),
    ]
