# Generated by Django 3.1 on 2020-08-26 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20200826_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateField(default=datetime.datetime(2020, 8, 26, 19, 19, 56, 693167, tzinfo=utc), verbose_name='Inicio de operaciones'),
        ),
    ]
