# Generated by Django 3.1 on 2020-08-26 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20200826_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateField(default=datetime.datetime(2020, 8, 26, 20, 7, 46, 441441, tzinfo=utc), verbose_name='Inicio de operaciones'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registerSAT',
            field=models.BooleanField(default=False, verbose_name='Registrado en el SAT'),
        ),
    ]
