# Generated by Django 3.1 on 2020-08-27 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20200826_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product1',
            field=models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Producto 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='product2',
            field=models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Producto 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='product3',
            field=models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Producto 3'),
        ),
        migrations.AddField(
            model_name='company',
            name='product4',
            field=models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Producto 4'),
        ),
        migrations.AddField(
            model_name='company',
            name='product5',
            field=models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Producto 5'),
        ),
        migrations.AddField(
            model_name='company',
            name='product6',
            field=models.ImageField(blank=True, null=True, upload_to='market', verbose_name='Producto 6'),
        ),
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 19, 0, 38, 535531, tzinfo=utc), verbose_name='Inicio de operaciones'),
        ),
    ]
