# Generated by Django 3.1 on 2020-08-27 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20200827_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='colony',
            field=models.CharField(max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.locality', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 19, 39, 19, 695694, tzinfo=utc), verbose_name='Inicio de operaciones'),
        ),
    ]
