# Generated by Django 2.1.5 on 2020-08-28 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20200827_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 18, 23, 57, 750559, tzinfo=utc), verbose_name='Inicio de operaciones'),
        ),
    ]
