# Generated by Django 3.1 on 2020-08-28 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_auto_20200828_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 18, 36, 51, 957231, tzinfo=utc), verbose_name='Inicio de operaciones'),
        ),
    ]
