# Generated by Django 3.1 on 2020-08-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20200828_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateField(verbose_name='Inicio de operaciones'),
        ),
    ]
