# Generated by Django 3.1 on 2020-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20200828_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='operation_start',
            field=models.DateTimeField(verbose_name='Inicio de operaciones'),
        ),
    ]
