# Generated by Django 3.1 on 2020-08-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20200828_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='locality',
        ),
        migrations.AlterField(
            model_name='company',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.city', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subactivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.subactivity', verbose_name='Actividad especifica'),
        ),
    ]
