# Generated by Django 3.1 on 2021-04-21 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Clave')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('content', models.CharField(max_length=2000, verbose_name='Contenido')),
                ('sended', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envio')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-sended'],
            },
        ),
    ]
