# Generated by Django 3.1 on 2020-08-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='key',
            field=models.SlugField(default='EIDE', max_length=100, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='phrase',
            field=models.TextField(max_length=100, verbose_name='Frase'),
        ),
    ]
