# Generated by Django 3.1 on 2020-08-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200814_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='key',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Clave'),
        ),
    ]
