# Generated by Django 3.1 on 2020-08-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200818_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='phrase',
        ),
    ]
