# Generated by Django 3.1 on 2020-08-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200811_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam in nunc molestie purus viverra bibendum. Aliquam fermentum tellus nec consequat venenatis. Mauris vitae hendrerit nunc, a faucibus neque. Fusce et purus erat. Nunc pellentesque augue et laoreet accumsan. Proin dictum enim sapien, ut aliquet diam lobortis nec. Suspendisse id neque eu magna aliquet fermentum. Proin faucibus iaculis urna eget dignissim.', verbose_name='Texto en vista previa'),
        ),
    ]
